export const ActionType = {
    SET_QUESTION_NUMBER: 'SET_QUESTION_NUMBER',
    UPDATE_ANSWERS: 'UPDATE_ANSWERS',
    UPDATE_LOADING_STATUS: 'UPDATE_LOADING_STATUS',
    UPDATE_CITIES_TO_CHOOSE_FROM: 'UPDATE_CITIES_TO_CHOOSE_FROM',
};
