export const ActionType = {
    SET_QUESTION_NUMBER: 'SET_QUESTION_NUMBER',
    UPDATE_ANSWERS: 'UPDATE_ANSWERS',
    UPDATE_LOADING_STATUS: 'UPDATE_LOADING_STATUS',
    UPDATE_TOURS_LOADING_STATUS: 'UPDATE_TOURS_LOADING_STATUS',
    UPDATE_CITIES_TO_CHOOSE_FROM: 'UPDATE_CITIES_TO_CHOOSE_FROM',
    SET_CHOSEN_CITY: 'SET_CHOSEN_CITY',
    GET_CITY_IMAGES: 'GET_CITY_IMAGES',
    GET_TOURS: 'GET_TOURS',
    RESET_CITY_DATA: 'RESET_CITY_DATA',
    RESET_TOURS: 'RESET_TOURS',
};
